"""The Expo project a React Native generation exports (DESIGN.md §13.1).

Modelled on Expo's own SDK blank template (expo-template-blank@sdk-57), with
the versions pinned in rn-runtime/expo-sdk.json, the same file the preview
runtime is built from (RNW-5). The host, index.js, wraps App in
SafeAreaProvider, as the preview does: without it, SafeAreaView applies no
insets on a device (§10).
"""

import json
from io import BytesIO
from pathlib import Path
from typing import Any, Mapping, Optional, cast
from zipfile import ZIP_DEFLATED, ZipFile

from react_native.export_assets import EmbeddedAsset, assets_module
from react_native.runtime_files import load_runtime

REPO_EXPO_SDK = Path(__file__).resolve().parents[2] / "rn-runtime" / "expo-sdk.json"
APP_NAME = "screenshot-to-code-app"

INDEX_JS = """import { registerRootComponent } from 'expo';
import { SafeAreaProvider } from 'react-native-safe-area-context';

import App from './App';

// App.jsx lays itself out inside SafeAreaView, which needs a provider above
// it to know the device's insets (the status bar, notch and home indicator).
function Root() {
  return (
    <SafeAreaProvider>
      <App />
    </SafeAreaProvider>
  );
}

registerRootComponent(Root);
"""

GITIGNORE = """node_modules/
.expo/
dist/
web-build/
expo-env.d.ts
.kotlin/
*.orig.*
*.jks
*.p8
*.p12
*.key
*.mobileprovision
.metro-health-check*
npm-debug.*
yarn-debug.*
yarn-error.*
.DS_Store
"""


def expo_sdk() -> dict[str, Any]:
    """The pins: from the built runtime (as deployed), else from the repo."""
    bundle = load_runtime()
    if bundle is not None:
        return cast(dict[str, Any], bundle.read_json(str(bundle.manifest["expoSdk"])))
    if REPO_EXPO_SDK.is_file():
        return cast(dict[str, Any], json.loads(REPO_EXPO_SDK.read_text(encoding="utf-8")))
    raise RuntimeError("rn-runtime/expo-sdk.json is missing")


def package_json(sdk: Mapping[str, Any]) -> str:
    package: dict[str, Any] = {
        "name": APP_NAME,
        "version": "1.0.0",
        "private": True,
        "main": "index.js",
        "scripts": {
            "start": "expo start",
            "android": "expo start --android",
            "ios": "expo start --ios",
            "web": "expo start --web",
        },
        "dependencies": dict(sorted(dict(sdk["dependencies"]).items())),
    }
    return json.dumps(package, indent=2) + "\n"


def app_json() -> str:
    app: dict[str, Any] = {
        "expo": {
            "name": "Screenshot to Code",
            "slug": APP_NAME,
            "version": "1.0.0",
            "orientation": "portrait",
            "userInterfaceStyle": "light",
            "ios": {"supportsTablet": True},
        }
    }
    return json.dumps(app, indent=2) + "\n"


def readme(sdk: Mapping[str, Any], assets: list[EmbeddedAsset], skipped: list[str]) -> str:
    major = str(sdk["sdk"]).split(".")[0]
    notes = ""
    if assets:
        notes += f"\n`assets.js` embeds the {len(assets)} image(s) `App.jsx` shows, so the app needs no server.\n"
    if skipped:
        listed = "\n".join(f"- {url}" for url in skipped)
        notes += f"\nThese URLs in `App.jsx` weren't embedded (not images, or unreachable when exported) and load from the network:\n\n{listed}\n"
    return f"""# Screenshot to Code: React Native screen

An [Expo](https://expo.dev) SDK {major} app generated by screenshot-to-code.

- `App.jsx`: the generated screen.
- `index.js`: registers it, wrapped in `SafeAreaProvider` so `SafeAreaView` knows the device's insets.
{notes}
## Run it

You need [Node.js](https://nodejs.org) 20 or later.

```bash
npm install
npx expo start
```

Then scan the QR code with [Expo Go](https://expo.dev/go) (SDK {major}) on an iPhone or Android phone, or press `i` or `a` to open a simulator or emulator. `npx expo start --web` runs it in a browser.

To check that it bundles for both platforms without a device:

```bash
npx expo export --platform ios --platform android
```
"""


def project_files(
    app_jsx: str,
    assets: list[EmbeddedAsset],
    skipped: Optional[list[str]] = None,
    sdk: Optional[Mapping[str, Any]] = None,
) -> dict[str, str]:
    sdk = sdk or expo_sdk()
    files = {
        "package.json": package_json(sdk),
        "app.json": app_json(),
        "index.js": INDEX_JS,
        "App.jsx": app_jsx,
        "README.md": readme(sdk, assets, skipped or []),
        ".gitignore": GITIGNORE,
    }
    if assets:
        files["assets.js"] = assets_module(assets)
    return files


def project_zip(files: Mapping[str, str], folder: str = APP_NAME) -> bytes:
    """The files under one top-level folder, as `npx create-expo-app` would lay them out."""
    buffer = BytesIO()
    with ZipFile(buffer, "w", ZIP_DEFLATED) as archive:
        for name, content in files.items():
            archive.writestr(f"{folder}/{name}", content)
    return buffer.getvalue()
